// Credit: https://github.com/nova-wallet/nova-utils/blob/master/dapps/dapps_dev.json

import { PredefinedDApps } from 'types/browser';
import i18n from 'utils/i18n/i18n';

export const DAppIconMap: Record<string, string> = {
  'app.soulswap.finance': 'https://soulswap.finance/favicon.png',
  'blockworks.co': 'https://raw.githubusercontent.com/SoulSwapFinance/assets/master/mobile/news/blockworks-logo.png',
  'cointelegraph.com': 'https://raw.githubusercontent.com/SoulSwapFinance/assets/master/mobile/news/cointelegraph-logo.png',
  'coindesk.com': 'https://raw.githubusercontent.com/SoulSwapFinance/assets/master/mobile/news/coindesk.png',
  'debank.com': 'https://debank.com/favicon.ico',
  'coingecko.com': 'https://www.coingecko.com/favicon.ico',
  'coinmarketcap.com': 'https://www.coinmarketcap.com/favicon.ico',
  'kintsugi.interlay.io': 'https://kintsugi.interlay.io/kintsugi/apple-touch-icon.png',
  'kanaria.rmrk.app': 'https://rmrk-unrestricted.mypinata.cloud/ipfs/QmSkVkPiMsr1Ryu7122KHoAHqsCrgQCWthNniykLKqbA5H',
  'distribution.acala.network': 'https://avatars.githubusercontent.com/u/54881907?s=200&v=4',
  'www.xdao.app': 'https://moonbeam.network/wp-content/uploads/2022/03/xDAO.png',
  'crowdloan.interlay.io': 'https://assets.coingecko.com/coins/images/26180/small/Interlay-Coinbase-2.png',
  'ace.web3go.xyz': 'https://ace.web3go.xyz/favicon.ico',
  'www.avault.network': 'https://www.avault.network/logo.png',
  'astr.domains': 'https://astr.domains/logo/logo_cic.png',
  'tfalpha.xyz': 'https://tfalpha.xyz/img/tfa-logo.png',
};

export const DAppTitleMap: Record<string, string> = {
  'app.soulswap.finance': 'SoulSwap DeFi', // √
  'app.uniswap.org': 'Uniswap DEX', // √
  'curve.fi': 'Curve Finance', // √
  'app.aave.com': 'Aave Protocol', // √
  'lido.fi': 'Liquid Staking for Digital Tokens', // √
  'defillama.com': 'DeFi Llama - DeFi Dashboard', // √
  'blur.io': 'Blur: NFT Marketplace for Pro Traders', // √
  'blockworks.co': 'Blockworks', // √
  'cointelegraph.com': 'CoinTelegraph', // √
  'coindesk.com': 'CoinDesk', // √
  'debank.com': 'DeBank', // √
  'polkadot.js.org': 'Polkadot/Substrate Portal', // √
  'app.solarbeam.io': 'Solarbeam', // √
  'tofunft.com': 'tofuNFT.com', // √
  'kusama.lido.fi': 'Lido', // √
  'polkadot.lido.fi': 'Lido', // √
  'moonbeam.curve.fi': 'Curve.fi', // √
  'app.basilisk.cloud': 'Basilisk', // √
  'damnedpiratessociety.io': 'Damned Pirates Society', // √ 
  'pioneer.bit.country': 'Bit Country - Metaverses made of 1 and 0 bits', // √
  'dappradar.com': 'DappRadar - The World’s Dapp Store', // √
  'chainlist.org': 'Chainlist', // √
  'www.portalbridge.com': 'Wormhole Bridge', // √
  'dapp.robonomics.network': 'Dapp Robonomics network', // √
  'app.bounce.finance': 'Bounce', // √
  'www.xdao.app': 'XDAO – MultiChain DAO Ecosystem', // √
  'sub.id': 'Sub ID: Substrate Addresses, Balances, Crowdloans and NFTs',
  'singular.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'dotmarketcap.com': 'DotMarketCap',

  'kanaria.rmrk.app': 'KANARIA',
  'bifrost.app': 'Bifrost',
  'portal.astar.network': 'Astar Portal - Astar & Shiden Network',
  'app.subsocial.network': 'Subsocial - Decentralized social network on Polkadot & IPFS',
  'kodadot.xyz': 'KodaDot - Kusama NFT Market Explorer',
  'app.parallel.fi': 'Parallel Finance',
  'polkadot.polkassembly.io': 'Polkassembly',
  'ksmcrowdloan.bit.country': 'Crowdloan - Bit.Country Pioneer Network',
  'crowdloan.parallel.fi': 'Parallel Finance',
  'kintsugi.interlay.io': 'Kintsugi',
  'distribution.acala.network': 'Acala Distribution Query',
  'apps.moonbeam.network': 'Moonbeam Network Apps',
  'app.solarflare.io': 'Solarflare',
  'app.beamswap.io': 'Beamswap',
  'app.stellaswap.com': 'StellaSwap - Leading Moonbeam DEX & DeFi Gateway',
  'app.impossible.finance': 'Impossible Finance',
  'singular-rmrk2-dev.vercel.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'app.arthswap.org': 'ArthSwap',
  'cbridge.celer.network': 'cBridge',
  'crowdloan.interlay.io': 'Interlay',
  'moonwell.fi': 'Moonwell',
  'apps.litentry.com': 'Litmus Network',
  'apps.darwinia.network': 'Darwinia',
  'polkawatch.app': 'Polkawatch',
  'staking.polkadot.network': 'Polkadot Staking Dashboard',
  'marketplace.moonsama.com': 'Moonsama',
  'game.evrloot.com': 'Join the Adventure -- evrloot',
  'www.dtmb.xyz': 'DOWNTOWN MOONBEAM',
  'portal.evolution.land': 'Evolution Land',
  'www.dotinsights.xyz': 'dotinsights | Polkadot & Kusama Ecosystem Map',
  'dotinsights.subwallet.app': 'dotinsights | Polkadot & Kusama Ecosystem Map',
  'app.phala.network': 'Phala App',
  'dex.zenlink.pro': 'Zenlink',
  'www.avault.network': 'Avault',
  'panoramaswap.app': 'Panorama Swap',
  'app.taigaprotocol.io': 'TAIGA',
  'astr.domains': 'Astar Web3 Domains (.astr) - Your Perfect NFT Domains',
  'event.tfalpha.xyz': 'Raffle & Claim Rewards',
  'tfalpha.xyz': 'Utopia & TF Alpha',
  'moons.money': 'Moon Web3 identity',
  'www.subsquare.io': 'SubSquare - Empower the governance of substrate.',
  'mint.azeropunks.com': 'AzeroPunks',
  'app.polkasafe.xyz': 'Polkasafe',
  'www.bananaswap.app': 'Bananaswap',
  'bluez.app': 'Bluez',
  'enterthemandala.app': 'Mandala',
  'www.mangata.finance': 'Mangata DEX',
  'app.dam.finance': 'DAM',
  'apps.acala.network': 'Acala Platform',
  'app.equilibrium.io': 'Equilibrium',
  'www.gear-tech.io': 'Gear Technologies | Crypto. Smarter.',
  'apps.karura.network': 'Karura Platform',
  'app.sirius.finance': 'Sirius Finance',
  'polkaverse.com': "PolkaVerse – Polkadot's Premier Social Network",
  'polkaswap.io': 'Swap - Polkaswap',
  'notifi.network': 'Notifi',
  'pods.spacers.app': 'Spacers NFT Pods Sale',
  'list.yieldbay.io': 'YieldBay',
  'app.fidi.tech': 'FiDi',
  'www.braindex.io': 'Braindex | Smart Dex Aggregator',
  'verse.bitcoin.com': 'Verse DEX',
};

export const predefinedDApps: PredefinedDApps = {
  categories: () => [
    {
      name: i18n.browser.defi,
      id: 'defi',
      theme: 'cyan',
    },
    {
      name: i18n.browser.nft,
      id: 'nft',
      theme: 'magenta',
    },
    {
      name: 'SOUL',
      id: 'soul',
      theme: 'purple',
    },
    {
      name: i18n.browser.utilities,
      id: 'utilities',
      theme: 'orange',
    },
    {
      name: 'GAMES',
      id: 'games',
      theme: 'yellow',
    },
    {
      name: i18n.browser.news,
      id: 'news',
      theme: 'blue',
    },
  ],
  dapps: [
    {
      name: 'SoulSwap',
      icon: 'https://soulswap.finance/favicon.png',
      id: 'app.soulswap.finance',
      url: 'https://app.soulswap.finance/',
      categories: ['defi', 'soul'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'DeBank',
      icon: 'https://debank.com/favicon.ico',
      id: 'debank.com',
      url: 'https://debank.com',
      categories: ['utilities'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Uniswap Interface',
      icon: 'https://uniswap.org/favicon.ico',
      id: 'app.uniswap.org',
      url: 'https://app.uniswap.org/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Aave Protocol',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/aave.png',
      id: 'app.aave.com',
      url: 'https://app.aave.com/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Rarible',
      icon: 'https://rarible.com/favicon.ico',
      id: 'rarible.com',
      url: 'https://rarible.com/',
      categories: ['nft'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'ArtZero | NFT Marketplace',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/artzero.png',
      id: 'https://a0.artzero.io',
      url: 'https://a0.artzero.io',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Basilisk Snek Swap',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/basilisk.png',
      id: 'app.basilisk.cloud',
      url: 'https://app.basilisk.cloud/#/trade',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Bounce',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/bounce-finance.png',
      id: 'app.bounce.finance/market',
      url: 'https://app.bounce.finance/market',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: 'Cosmize Experience',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/cosmize.png',
    //   id: 'app.cosmize.io',
    //   url: 'https://app.cosmize.io',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'DAM',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/dam-finance.png',
    //   id: 'app.dam.finance',
    //   url: 'https://app.dam.finance/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Equilibrium',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/equilibrium.png',
    //   id: 'app.equilibrium.io',
    //   url: 'https://app.equilibrium.io/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'FiDi',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/fidi.png',
    //   id: 'app.fidi.tech',
    //   url: 'https://app.fidi.tech/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Impossible Finance',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/impossible-finance.png',
    //   id: 'app.impossible.finance',
    //   url: 'https://app.impossible.finance/explore',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    // {
    //   name: 'Parallel Finance',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/parallel.png',
    //   id: 'app.parallel.fi',
    //   url: 'https://app.parallel.fi/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Phala App',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/phala-network.png',
    //   id: 'app.phala.network',
    //   url: 'https://app.phala.network/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Polkasafe',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/polkasafe.png',
    //   id: 'app.polkasafe.xyz',
    //   url: 'https://app.polkasafe.xyz/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Sirius Finance',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/sirius-finance.png',
    //   id: 'app.sirius.finance',
    //   url: 'https://app.sirius.finance/#/swap',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: 'Stellaswap',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/stellaswap.png',
      id: 'app.stellaswap.com',
      url: 'https://app.stellaswap.com/exchange/swap',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Acala Platform',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/acala.png',
      id: 'apps.acala.network',
      url: 'https://apps.acala.network/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Darwinia App',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/darwinia.png',
      id: 'apps.darwinia.network',
      url: 'https://apps.darwinia.network/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: 'Karura Platform',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/karura.png',
    //   id: 'apps.karura.network',
    //   url: 'https://apps.karura.network/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: 'Moonbeam',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/moonbeam-network.png',
      id: 'apps.moonbeam.network/moonbeam',
      url: 'https://apps.moonbeam.network/moonbeam',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Moonriver',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/moonriver.png',
      id: 'apps.moonbeam.network/moonriver',
      url: 'https://apps.moonbeam.network/moonriver',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    // {
    //   name: 'ArtZero | NFT Marketplace (Astar)',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/artzero.png',
    //   id: 'astar.artzero.io',
    //   url: 'https://astar.artzero.io/',
    //   categories: ['nft'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Bifrost App',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/bifrost-polkadot.png',
    //   id: 'bifrost.app',
    //   url: 'https://bifrost.app/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Bluez',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/bluez.png',
    //   id: 'bluez.app',
    //   url: 'https://bluez.app/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: 'Blur | NFT Marketplace for Traders',
      icon: 'https://blur.io/favicons/180.png',
      id: 'blur.io',
      url: 'https://blur.io/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: 'cBridge | Binance Bridge',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/celer-cbridge.png',
    //   id: 'cbridge.celer.network',
    //   url: 'https://cbridge.celer.network/#/transfer',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    {
      name: 'Chainlist',
      icon: 'https://chainlist.org/favicon.ico',
      id: 'chainlist.org',
      url: 'https://chainlist.org/',
      categories: ['utilities'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Curve Finance',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/curve.png',
      id: 'curve.fi',
      url: 'https://curve.fi/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Damned Pirates Society',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/the-damned-pirates-society.png',
      id: 'damnedpiratessociety.io',
      url: 'https://damnedpiratessociety.io/',
      categories: ['nft'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Robonomics',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/robonomics.png',
      id: 'dapp.robonomics.network',
      url: 'https://dapp.robonomics.network/#/staking/',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'DappRadar',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/dappradar.png',
      id: 'dappradar.com',
      url: 'https://dappradar.com/',
      categories: ['utilities'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    // {
    //   name: 'Zenlink',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/zenlink.png',
    //   id: 'dex.zenlink.pro',
    //   url: 'https://dex.zenlink.pro/#/swap',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'dotinsights | Polkadot & Kusama Ecosystem Map',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/dotinsights.png',
    //   id: 'dotinsights.subwallet.app',
    //   url: 'https://dotinsights.subwallet.app/',
    //   categories: ['utilities'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: 'Dotmarketcap',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/dotmarketcap.png',
      id: 'dotmarketcap.com',
      url: 'https://dotmarketcap.com/',
      categories: ['utilities'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: 'Mandala',
    //   icon: 'https://enterthemandala.app/SriChakraRainbow.png',
    //   id: 'enterthemandala.app',
    //   url: 'https://enterthemandala.app/HomePage',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: "HydraDX | DOT Liquidity Monster",
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/hydradx.png',
      id: 'hydradx.io',
      url: 'https://hydradx.io',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: 'InkWhale | Stake and Farm',
    //   icon: 'https://www.inkwhale.net/apple-touch-icon.png',
    //   id: 'inkwhale.net',
    //   url: 'https://inkwhale.net',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Kanaria',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/kanaria.png',
    //   id: 'kanaria.rmrk.app',
    //   url: 'https://kanaria.rmrk.app/',
    //   categories: ['nft'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Kintsugi Hub',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/kintsugi.png',
    //   id: 'kintsugi.interlay.io',
    //   url: 'https://kintsugi.interlay.io/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'KodaDot',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/kodadot.png',
    //   id: 'kodadot.xyz',
    //   url: 'https://kodadot.xyz/',
    //   categories: ['nft'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Kusama Lido',
    //   icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/LIDO_KSM.svg',
    //   id: 'kusama.lido.fi',
    //   url: 'https://kusama.lido.fi/',
    //   categories: ['defi', 'evm'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    {
      name: 'LidoFi | Liquid Staking',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/lido.png',
      id: 'lido.fi/#networks',
      url: 'https://lido.fi/#networks',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'DeFi Llama',
      icon: 'https://defillama.com/favicon.ico',
      id: 'defillama.com',
      url: 'https://defillama.com',
      categories: ['utilities'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: 'YieldBay',
    //   icon: 'https://list.yieldbay.io/favicon/favicon.ico',
    //   id: 'list.yieldbay.io',
    //   url: 'https://list.yieldbay.io/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Moonsama',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/moonsama.png',
    //   id: 'marketplace.moonsama.com',
    //   url: 'https://marketplace.moonsama.com/',
    //   categories: ['nft'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    // {
    //   name: 'Moonbeam Curve',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/curve.png',
    //   id: 'moonbeam.curve.fi',
    //   url: 'https://moonbeam.curve.fi/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    {
      name: 'Moonwell',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonwell.svg',
      id: 'moonwell.fi',
      url: 'https://moonwell.fi',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    // {
    //   name: 'Notifi',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/notifi-network.png',
    //   id: 'notifi.network',
    //   url: 'https://notifi.network/dashboard',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Panorama Swap',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/panorama-swap.png',
    //   id: 'panoramaswap.app',
    //   url: 'https://panoramaswap.app/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: 'Bit.Country Pioneer Metaverse',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/bit.country-pioneer.png',
      id: 'pioneer.bit.country',
      url: 'https://pioneer.bit.country/',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Polkadot.js',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/polkadot-%7B.js%7D.png',
      id: 'polkadot.js.org',
      url: 'https://polkadot.js.org/apps/#',
      categories: ['utilities'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: 'Polkadot Lido',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/lido.png',
    //   id: 'polkadot.lido.fi',
    //   url: 'https://polkadot.lido.fi/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    {
      name: 'Polkaswap',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/polkaswap.png',
      id: 'polkaswap.io',
      url: 'https://polkaswap.io/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    // {
    //   name: "PolkaVerse u2013 Polkadot's Premier Social Network",
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/polkaverse.png',
    //   id: 'polkaverse.com',
    //   url: 'https://polkaverse.com/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: 'Astar DApp Hub',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/astar-network.png',
      id: 'portal.astar.network',
      url: 'https://portal.astar.network/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Singular',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/singular.png',
      id: 'singular.app',
      url: 'https://singular.app/',
      categories: ['nft'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Polkadot Staking Dashboard',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/polkadot.png',
      id: 'staking.polkadot.network',
      url: 'https://staking.polkadot.network/dashboard#/overview',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Sub ID: Substrate Addresses, Balances, Crowdloans and NFTs',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/sub-id.png',
      id: 'sub.id',
      url: 'https://sub.id/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'TofuNFT',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/tofunft.png',
      id: 'tofunft.com',
      url: 'https://tofunft.com/',
      categories: ['nft'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    // {
    //   name: 'Verse DEX | Bitcoin.comu00e2u20acu2122s official decentralized exchange',
    //   icon: 'https://verse.bitcoin.com/images/favicon.png',
    //   id: 'verse.bitcoin.com',
    //   url: 'https://verse.bitcoin.com/#/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: true,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Avault',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/avault.png',
    //   id: 'www.avault.network',
    //   url: 'https://www.avault.network/vault',
    //   categories: ['evm'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    // {
    //   name: 'Bananaswap',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/bananaswap.png',
    //   id: 'www.bananaswap.app',
    //   url: 'https://www.bananaswap.app/#/swap',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Braindex | Smart Dex Aggregator',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/braindex.png',
    //   id: 'www.braindex.io',
    //   url: 'https://www.braindex.io/swap',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Gear Technologies | Crypto. Smarter.',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/gear.png',
    //   id: 'www.gear-tech.io',
    //   url: 'https://www.gear-tech.io/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    // {
    //   name: 'Mangata - The DEX of the future',
    //   icon: 'https://dotinsights.subwallet.app/assets/images/projects/mangata.png',
    //   id: 'www.mangata.finance',
    //   url: 'https://www.mangata.finance/',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: false,
    // },
    {
      name: 'Portal Token Bridge',
      icon: 'https://www.portalbridge.com/favicon.ico',
      id: 'www.portalbridge.com',
      url: 'https://www.portalbridge.com/',
      categories: ['defi', 'utilities'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'XDAO',
      icon: 'https://dotinsights.subwallet.app/assets/images/projects/xdao.png',
      id: 'www.xdao.app',
      url: 'https://www.xdao.app/137',
      categories: ['defi'], // DAO
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    // {
    //   name: 'Oxalus - NFT Social Commerce Platform',
    //   icon: 'https://oxalus.io/favicon.ico',
    //   id: 'www.oxalus.io',
    //   url: 'https://oxalus.io',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    // {
    //   name: 'Birdeye',
    //   icon: 'https://birdeye.so/logo.png',
    //   id: 'www.birdeye.so',
    //   url: 'https://birdeye.so',
    //   categories: ['defi'],
    //   isSupportSubstrateAccount: false,
    //   isSupportEthereumAccount: true,
    // },
    {
      name: 'AZERO.ID – Domain Service on Aleph Zero',
      icon: 'https://azero.id/favicon.ico',
      id: 'www.azero.id',
      url: 'https://azero.id',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Blockworks',
      icon: 'https://raw.githubusercontent.com/SoulSwapFinance/assets/master/mobile/news/blockworks-logo.png',
      id: 'blockworks.co',
      url: 'https://blockworks.co',
      categories: ['news'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: true,
    },
    {
      name: 'CoinTelegraph',
      icon: 'https://raw.githubusercontent.com/SoulSwapFinance/assets/master/mobile/news/cointelegraph-logo.png',
      id: 'cointelegraph.com',
      url: 'https://cointelegraph.com',
      categories: ['news'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: true,
    },
    {
      name: 'CoinDesk',
      icon: 'https://raw.githubusercontent.com/SoulSwapFinance/assets/master/mobile/news/coindesk.png',
      id: 'coindesk.com',
      url: 'https://coindesk.com',
      categories: ['news'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: true,
    },
    {
      name: 'CoinGecko',
      icon: 'https://www.coingecko.com/favicon.ico',
      id: 'coingecko.com',
      url: 'https://www.coingecko.com/en/coins/soul-swap',
      categories: ['news'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: true,
    },
    {
      name: 'CoinMarketCap',
      icon: 'https://www.coinmarketcap.com/favicon.ico',
      id: 'coinmarketcap.com',
      url: 'https://coinmarketcap.com/currencies/soulswap-finance/',
      categories: ['news'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: true,
    },
  ],
};
